# setup
setup: scan

# Loss
criterion: scan
criterion_kwargs:
   entropy_weight: 5.0  # 5.0
   weight_t: 0.05
   alpha: 0.1

# Weight update
update_cluster_head_only: True # Update full network in SCAN
num_heads: 1 # Only use one head

# Model
backbone: resnet18

# Dataset
train_db_name: cifar-10
val_db_name: cifar-10
num_classes: 10
num_neighbors: 20

# Transformations
augmentation_strategy: ours # cutmix
augmentation_kwargs:
   crop_size: 32
   normalize:
      mean: [0.4914, 0.4822, 0.4465]
      std: [0.2023, 0.1994, 0.2010]
   num_strong_augs: 4
   cutout_kwargs:
     n_holes: 1
     length: 16
     random: True

transformation_kwargs:
   crop_size: 32
   normalize:
      mean: [x / 255.0 for x in [125.3, 123.0, 113.9]] # [0.4914, 0.4822, 0.4465]
      std:  [x / 255.0 for x in [63.0, 62.1, 66.7]] # [0.2023, 0.1994, 0.2010]

# Hyperparameters
optimizer: adam
optimizer_kwargs:
   lr: 0.0001
   weight_decay: 0.0001
epochs: 100
batch_size: 128
num_workers: 8 #8

# Scheduler
scheduler: constant
